sudo: false
language: python
env:
  - TOXENV=py26
  - TOXENV=py27
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.4
install:
  - pip install tox
script:
  - tox
after_success:
  - coveralls
